/* Generated by Yosys 0.9+3710 (git sha1 2116c585, clang 12.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "bram_rom.v:1.1-42.10" *)
module top();
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _00_;
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _01_;
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _02_;
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _03_;
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _04_;
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _05_;
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _06_;
  (* force_downto = 32'd1 *)
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "25" *)
  wire [25:0] _07_;
  (* force_downto = 32'd1 *)
  (* src = "bram_rom.v:27.9-27.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "25" *)
  wire [25:0] _08_;
  (* unused_bits = "0 1 2 3 4 5 6 7 8 9" *)
  wire [9:0] _09_;
  (* src = "bram_rom.v:3.7-3.10" *)
  wire clk;
  (* src = "bram_rom.v:25.12-25.15" *)
  (* unused_bits = "25" *)
  wire [25:0] ctr;
  (* src = "bram_rom.v:7.13-7.17" *)
  wire [7:0] leds;
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _10_ (
    .I({ 2'h3, ctr[1:0] }),
    .Q(_08_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _11_ (
    .I({ 1'h1, ctr[2:0] }),
    .Q(_08_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _12_ (
    .I(ctr[3:0]),
    .Q(_08_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _13_ (
    .I({ 2'h3, ctr[4], _04_ }),
    .Q(_08_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _14_ (
    .I(ctr[3:0]),
    .Q(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _15_ (
    .I({ 1'h1, ctr[5:4], _04_ }),
    .Q(_08_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _16_ (
    .I({ ctr[6:4], _04_ }),
    .Q(_08_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _17_ (
    .I({ 2'h3, ctr[7], _05_ }),
    .Q(_08_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _18_ (
    .I({ ctr[6:4], _04_ }),
    .Q(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _19_ (
    .I({ 1'h1, ctr[8:7], _05_ }),
    .Q(_08_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _20_ (
    .I({ ctr[9:7], _05_ }),
    .Q(_08_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _21_ (
    .I({ 2'h3, ctr[10], _06_ }),
    .Q(_08_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _22_ (
    .I({ ctr[9:7], _05_ }),
    .Q(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _23_ (
    .I({ 1'h1, ctr[11:10], _06_ }),
    .Q(_08_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _24_ (
    .I({ ctr[12:10], _06_ }),
    .Q(_08_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _25_ (
    .I({ 2'h3, ctr[13], _00_ }),
    .Q(_08_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _26_ (
    .I({ ctr[12:10], _06_ }),
    .Q(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _27_ (
    .I({ 1'h1, ctr[14:13], _00_ }),
    .Q(_08_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _28_ (
    .I({ ctr[15:13], _00_ }),
    .Q(_08_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _29_ (
    .I({ 2'h3, ctr[16], _01_ }),
    .Q(_08_[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _30_ (
    .I({ ctr[15:13], _00_ }),
    .Q(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _31_ (
    .I({ 1'h1, ctr[17:16], _01_ }),
    .Q(_08_[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _32_ (
    .I({ ctr[18:16], _01_ }),
    .Q(_08_[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _33_ (
    .I({ 2'h3, ctr[19], _02_ }),
    .Q(_08_[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _34_ (
    .I({ ctr[18:16], _01_ }),
    .Q(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _35_ (
    .I({ 1'h1, ctr[20:19], _02_ }),
    .Q(_08_[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _36_ (
    .I({ ctr[21:19], _02_ }),
    .Q(_08_[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _37_ (
    .I({ 2'h3, ctr[22], _03_ }),
    .Q(_08_[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _38_ (
    .I({ ctr[21:19], _02_ }),
    .Q(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _39_ (
    .I({ 1'h1, ctr[23:22], _03_ }),
    .Q(_08_[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _40_ (
    .I({ ctr[24:22], _03_ }),
    .Q(_08_[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:9.33-9.88" *)
  LUT #(
    .INIT(16'h5555),
    .K(32'sd4)
  ) _41_ (
    .I({ 3'h7, ctr[0] }),
    .Q(_07_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _42_ (
    .CLK(clk),
    .D(_08_[16]),
    .Q(ctr[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _43_ (
    .CLK(clk),
    .D(_08_[17]),
    .Q(ctr[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _44_ (
    .CLK(clk),
    .D(_08_[18]),
    .Q(ctr[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _45_ (
    .CLK(clk),
    .D(_08_[19]),
    .Q(ctr[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _46_ (
    .CLK(clk),
    .D(_08_[20]),
    .Q(ctr[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _47_ (
    .CLK(clk),
    .D(_08_[21]),
    .Q(ctr[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _48_ (
    .CLK(clk),
    .D(_08_[22]),
    .Q(ctr[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _49_ (
    .CLK(clk),
    .D(_08_[23]),
    .Q(ctr[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _50_ (
    .CLK(clk),
    .D(_08_[24]),
    .Q(ctr[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _51_ (
    .CLK(clk),
    .D(_07_[0]),
    .Q(ctr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _52_ (
    .CLK(clk),
    .D(_08_[1]),
    .Q(ctr[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _53_ (
    .CLK(clk),
    .D(_08_[2]),
    .Q(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _54_ (
    .CLK(clk),
    .D(_08_[3]),
    .Q(ctr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _55_ (
    .CLK(clk),
    .D(_08_[4]),
    .Q(ctr[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _56_ (
    .CLK(clk),
    .D(_08_[5]),
    .Q(ctr[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _57_ (
    .CLK(clk),
    .D(_08_[6]),
    .Q(ctr[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _58_ (
    .CLK(clk),
    .D(_08_[7]),
    .Q(ctr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _59_ (
    .CLK(clk),
    .D(_08_[8]),
    .Q(ctr[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _60_ (
    .CLK(clk),
    .D(_08_[9]),
    .Q(ctr[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _61_ (
    .CLK(clk),
    .D(_08_[10]),
    .Q(ctr[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _62_ (
    .CLK(clk),
    .D(_08_[11]),
    .Q(ctr[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _63_ (
    .CLK(clk),
    .D(_08_[12]),
    .Q(ctr[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _64_ (
    .CLK(clk),
    .D(_08_[13]),
    .Q(ctr[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _65_ (
    .CLK(clk),
    .D(_08_[14]),
    .Q(ctr[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _66_ (
    .CLK(clk),
    .D(_08_[15]),
    .Q(ctr[15])
  );
  (* BEL = "IOTILE(04,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:5.49-5.67" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd1),
    .OUTPUT_USED(32'sd0)
  ) clk_ibuf (
    .O(clk)
  );
  (* BEL = "IOTILE(02,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:23.49-23.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led0_obuf (
    .I(leds[0])
  );
  (* BEL = "IOTILE(01,09):alta_rio03" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:21.49-21.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led1_obuf (
    .I(leds[1])
  );
  (* BEL = "IOTILE(00,09):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:19.49-19.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led2_obuf (
    .I(leds[2])
  );
  (* BEL = "IOTILE(00,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:17.49-17.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led3_obuf (
    .I(leds[3])
  );
  (* BEL = "IOTILE(01,09):alta_rio01" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:15.49-15.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led4_obuf (
    .I(leds[4])
  );
  (* BEL = "IOTILE(06,09):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:13.49-13.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led5_obuf (
    .I(leds[5])
  );
  (* BEL = "IOTILE(07,01):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:11.49-11.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led6_obuf (
    .I(leds[6])
  );
  (* BEL = "IOTILE(02,01):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:9.49-9.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led7_obuf (
    .I(leds[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "bram_rom.v:31.14-37.2" *)
  GENERIC_BRAM #(
    .INIT_VAL(4608'h6e93bf3c9bf8682a93d25743848ead9740b8f17ac014fb9ed4e363fb1a4e642656b182cb2e112035e1934293ccc05dcfa9129651934418c75e414fbb01620186b08359d7b0d0c8559b74709a375663f2b2797a8031ac70efeba215af27f225e025392fc139a9f439ac83d9172f252d585fcf0a56d1df0ae7477ff14e39ca3b217d0a5b9a368f3ba5e6df4fce77b10f0608d68bc637532df080e7c96952c33a191b776170163aedca063c3a5cb83ece379df68e77990fd0478aadc4ba45bc8242206fbd69bc1b16de0f45a5e86c784cb35c4da160f82ecf6d560707e1c2d3762653a3084f2808befe855ebdf44d56b47a067cf89c900880ddd32529ba729ae84f36ed473d73b4fe36d17fae1e6909203234bcf1d78c38e8cc297073614ce0ab6e62ed0962b54df273826aa92e1f7097cd96604df89c77419d9fe7d3eeb64ec14867ba0c5f09bd13fd0aaee9585a251c6223d0f18ddec939a30dcbc60b8daa69d1ecb58ab240ceb89ef8d01c2749eb0a36534aca135f1c329c96e2a85346d745c273d91639b3204dd5bf42a0fd213487423fcf82660b10f1b22681ab6f43a78a4c1131dd33f52374b5b4296936cebdf7125e5feec55d285e3db973fce42936e4e88ebc28871350632c887e3a73b9c2c36ae977d08b71c7f2b950961e13179db38d00a7015106fb4c2f370e7dd54024f47db71370edc546dd00fa43c6be28e8ed9ca4c5d530217d451ac8a91e59303dcc6abb5e6135c0cf73b3400bb63d77f8ff1cc440dba04b59e4b5725a58fbc37e19cd88744e2725695d5782228301b8c10743)
  ) ram_inst (
    .AddressA(ctr[24:13]),
    .AsyncReset0(1'h0),
    .Clk0(clk),
    .DataOutA({ _09_, leds }),
    .WeRenA(1'h0)
  );
  assign _07_[25:1] = ctr[25:1];
  assign _08_[0] = _07_[0];
endmodule
