/* Generated by Yosys 0.9+2406 (git sha1 371af7da, clang 10.0.1 -fPIC -Os) */

(* top =  1  *)
(* src = "rs232demo.v:7.1-65.10" *)
module top();
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:188|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" *)
  wire _000_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:112|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" *)
  wire _001_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:112|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" *)
  wire _002_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:112|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" *)
  wire _003_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:147|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" *)
  wire _004_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:147|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" *)
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:158.12-158.21" *)
  wire _052_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:158.12-158.21" *)
  wire _053_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:188|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:256" *)
  wire _054_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:188|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:256" *)
  wire _055_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5" *)
  wire _056_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5" *)
  wire _057_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5" *)
  wire _058_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5" *)
  wire _059_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5" *)
  wire _060_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _061_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _062_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _063_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _064_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _065_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _066_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _067_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _068_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _069_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _070_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _071_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _072_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _073_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _074_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _075_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _076_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _077_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _078_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _079_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _080_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _081_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5" *)
  wire _082_;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:105" *)
  wire _083_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _084_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _085_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _086_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _087_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _088_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _089_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _090_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _091_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _092_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _093_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _094_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _095_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _096_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _097_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _098_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _099_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _100_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _101_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5" *)
  wire _102_;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:173.2-191.5" *)
  wire _103_;
  (* src = "rs232demo.v:37.8-37.12" *)
  wire LED1;
  (* src = "rs232demo.v:34.8-34.12" *)
  wire LED2;
  (* src = "rs232demo.v:31.8-31.12" *)
  wire LED3;
  (* src = "rs232demo.v:28.8-28.12" *)
  wire LED4;
  (* src = "rs232demo.v:25.8-25.12" *)
  wire LED5;
  (* src = "rs232demo.v:17.8-17.10" *)
  wire RX;
  (* src = "rs232demo.v:21.8-21.10" *)
  wire TX;
  (* src = "rs232demo.v:13.8-13.11" *)
  wire clk;
  (* init = 1'h1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:72.13-72.17" *)
  wire \recv.LED1 ;
  (* init = 1'h0 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:73.13-73.17" *)
  wire \recv.LED2 ;
  (* init = 1'h1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:74.13-74.17" *)
  wire \recv.LED3 ;
  (* init = 1'h0 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:75.13-75.17" *)
  wire \recv.LED4 ;
  (* init = 1'h1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:76.13-76.17" *)
  wire \recv.LED5 ;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:71.9-71.11" *)
  wire \recv.RX ;
  (* init = 4'h0 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:82.12-82.19" *)
  wire [3:0] \recv.bit_cnt ;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:78.12-78.18" *)
  wire [7:0] \recv.buffer ;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:79.6-79.18" *)
  wire \recv.buffer_valid ;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:70.9-70.12" *)
  wire \recv.clk ;
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:81.32-81.41" *)
  wire [7:0] \recv.cycle_cnt ;
  (* init = 1'h0 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:83.6-83.10" *)
  wire \recv.recv ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:133.9-133.13" *)
  wire \send.LED1 ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:134.9-134.13" *)
  wire \send.LED2 ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:135.9-135.13" *)
  wire \send.LED3 ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:136.9-136.13" *)
  wire \send.LED4 ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:137.9-137.13" *)
  wire \send.LED5 ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:132.9-132.11" *)
  wire \send.TX ;
  (* init = 5'h00 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:143.12-143.19" *)
  wire [4:0] \send.bit_cnt ;
  (* init = 6'h3c *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:144.12-144.20" *)
  wire [5:0] \send.byte_cnt ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:131.9-131.12" *)
  wire \send.clk ;
  (* init = 8'h00 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:142.25-142.34" *)
  wire [7:0] \send.cycle_cnt ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:159.6-159.14" *)
  wire \send.data_bit ;
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:158.12-158.21" *)
  (* unused_bits = "0 1 2 5" *)
  wire [7:0] \send.data_byte ;
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h1111),
    .K(32'sd4)
  ) _104_ (
    .I({ 2'h3, _014_, _073_ }),
    .Q(_082_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _105_ (
    .I({ 2'h3, _083_, _050_ }),
    .Q(_073_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _106_ (
    .I({ 2'h3, \recv.recv , _051_ }),
    .Q(_050_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _107_ (
    .I({ 2'h3, _013_, _012_ }),
    .Q(_051_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0100),
    .K(32'sd4)
  ) _108_ (
    .I({ \recv.cycle_cnt [2], \recv.cycle_cnt [7], \recv.cycle_cnt [5:4] }),
    .Q(_012_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0100),
    .K(32'sd4)
  ) _109_ (
    .I({ \recv.cycle_cnt [6], \recv.cycle_cnt [3], \recv.cycle_cnt [1:0] }),
    .Q(_013_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h1000),
    .K(32'sd4)
  ) _110_ (
    .I({ \recv.bit_cnt [3], \recv.bit_cnt [0], \recv.bit_cnt [2:1] }),
    .Q(_083_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h4444),
    .K(32'sd4)
  ) _111_ (
    .I({ 2'h3, RX, \recv.recv  }),
    .Q(_014_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _112_ (
    .I({ 1'h1, _015_, \recv.buffer [1:0] }),
    .Q(_065_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h4444),
    .K(32'sd4)
  ) _113_ (
    .I({ 2'h3, _050_, _083_ }),
    .Q(_015_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _114_ (
    .I({ 1'h1, _015_, \recv.buffer [2:1] }),
    .Q(_066_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _115_ (
    .I({ 1'h1, _015_, \recv.buffer [3:2] }),
    .Q(_067_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _116_ (
    .I({ 1'h1, _015_, \recv.buffer [4:3] }),
    .Q(_068_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _117_ (
    .I({ 1'h1, _015_, \recv.buffer [5:4] }),
    .Q(_069_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _118_ (
    .I({ 1'h1, _015_, \recv.buffer [6:5] }),
    .Q(_070_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _119_ (
    .I({ 1'h1, _015_, \recv.buffer [7:6] }),
    .Q(_071_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hcaca),
    .K(32'sd4)
  ) _120_ (
    .I({ 1'h1, _015_, RX, \recv.buffer [7] }),
    .Q(_072_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hacac),
    .K(32'sd4)
  ) _121_ (
    .I({ 1'h1, \recv.cycle_cnt [0], _016_, _014_ }),
    .Q(_074_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h4444),
    .K(32'sd4)
  ) _122_ (
    .I({ 2'h3, \recv.recv , _051_ }),
    .Q(_016_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h3cf5),
    .K(32'sd4)
  ) _123_ (
    .I({ \recv.recv , \recv.cycle_cnt [1:0], RX }),
    .Q(_075_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'hbac0),
    .K(32'sd4)
  ) _124_ (
    .I({ \recv.cycle_cnt [2], _016_, _001_, _014_ }),
    .Q(_076_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _125_ (
    .I({ 2'h3, \recv.cycle_cnt [1:0] }),
    .Q(_001_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1c1c),
    .K(32'sd4)
  ) _126_ (
    .I({ 1'h1, \recv.cycle_cnt [3], _017_, _018_ }),
    .Q(_077_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _127_ (
    .I({ 2'h3, \recv.recv , _002_ }),
    .Q(_017_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h8080),
    .K(32'sd4)
  ) _128_ (
    .I({ 1'h1, \recv.cycle_cnt [2:0] }),
    .Q(_002_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h1111),
    .K(32'sd4)
  ) _129_ (
    .I({ 2'h3, RX, \recv.recv  }),
    .Q(_018_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0788),
    .K(32'sd4)
  ) _130_ (
    .I({ \recv.cycle_cnt [4], _018_, \recv.cycle_cnt [3], _017_ }),
    .Q(_078_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h3e3e),
    .K(32'sd4)
  ) _131_ (
    .I({ 1'h1, \recv.cycle_cnt [5], _019_, _018_ }),
    .Q(_079_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h8080),
    .K(32'sd4)
  ) _132_ (
    .I({ 1'h1, \recv.cycle_cnt [4:3], _017_ }),
    .Q(_019_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'hbac0),
    .K(32'sd4)
  ) _133_ (
    .I({ \recv.cycle_cnt [6], _016_, _003_, _014_ }),
    .Q(_080_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _134_ (
    .I({ \recv.cycle_cnt [5:3], _002_ }),
    .Q(_003_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1c1c),
    .K(32'sd4)
  ) _135_ (
    .I({ 1'h1, \recv.cycle_cnt [7], _020_, _018_ }),
    .Q(_081_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h8080),
    .K(32'sd4)
  ) _136_ (
    .I({ 1'h1, \recv.recv , \recv.cycle_cnt [6], _003_ }),
    .Q(_020_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1c1c),
    .K(32'sd4)
  ) _137_ (
    .I({ 1'h1, \recv.bit_cnt [0], _050_, _018_ }),
    .Q(_061_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1c1c),
    .K(32'sd4)
  ) _138_ (
    .I({ 1'h1, \recv.bit_cnt [1], _021_, _018_ }),
    .Q(_062_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _139_ (
    .I({ 2'h3, \recv.bit_cnt [0], _050_ }),
    .Q(_021_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0788),
    .K(32'sd4)
  ) _140_ (
    .I({ \recv.bit_cnt [2], _018_, \recv.bit_cnt [1], _021_ }),
    .Q(_063_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1c1c),
    .K(32'sd4)
  ) _141_ (
    .I({ 1'h1, \recv.bit_cnt [3], _022_, _018_ }),
    .Q(_064_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _142_ (
    .I({ \recv.bit_cnt [0], \recv.bit_cnt [2:1], _050_ }),
    .Q(_022_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _143_ (
    .I({ 2'h3, \recv.LED5 , _023_ }),
    .Q(_060_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h4000),
    .K(32'sd4)
  ) _144_ (
    .I({ _024_, \recv.buffer [0], \recv.buffer [2], \recv.buffer [3] }),
    .Q(_023_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h4444),
    .K(32'sd4)
  ) _145_ (
    .I({ 2'h3, _025_, \recv.buffer [1] }),
    .Q(_024_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h8080),
    .K(32'sd4)
  ) _146_ (
    .I({ 1'h1, \recv.buffer [5:4], _026_ }),
    .Q(_025_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1010),
    .K(32'sd4)
  ) _147_ (
    .I({ 1'h1, \recv.buffer_valid , \recv.buffer [7:6] }),
    .Q(_026_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _148_ (
    .I({ 2'h3, \recv.LED4 , _027_ }),
    .Q(_059_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h1000),
    .K(32'sd4)
  ) _149_ (
    .I({ \recv.buffer [2], _024_, \recv.buffer [3], \recv.buffer [0] }),
    .Q(_027_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _150_ (
    .I({ 2'h3, \recv.LED3 , _028_ }),
    .Q(_058_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h1000),
    .K(32'sd4)
  ) _151_ (
    .I({ _029_, \recv.buffer [0], \recv.buffer [3:2] }),
    .Q(_028_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _152_ (
    .I({ 2'h3, \recv.buffer [1], _025_ }),
    .Q(_029_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _153_ (
    .I({ 2'h3, \recv.LED2 , _030_ }),
    .Q(_057_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0100),
    .K(32'sd4)
  ) _154_ (
    .I({ _029_, \recv.buffer [3], \recv.buffer [0], \recv.buffer [2] }),
    .Q(_030_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _155_ (
    .I({ 2'h3, \recv.LED1 , _031_ }),
    .Q(_056_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h1000),
    .K(32'sd4)
  ) _156_ (
    .I({ _024_, \recv.buffer [0], \recv.buffer [3:2] }),
    .Q(_031_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1414),
    .K(32'sd4)
  ) _157_ (
    .I({ 1'h1, \send.bit_cnt [0], _011_, _010_ }),
    .Q(_084_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _158_ (
    .I({ 2'h3, _033_, _032_ }),
    .Q(_011_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0001),
    .K(32'sd4)
  ) _159_ (
    .I({ \send.cycle_cnt [7], \send.cycle_cnt [5:3] }),
    .Q(_032_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h1000),
    .K(32'sd4)
  ) _160_ (
    .I({ \send.cycle_cnt [2], \send.cycle_cnt [6], \send.cycle_cnt [1:0] }),
    .Q(_033_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h4040),
    .K(32'sd4)
  ) _161_ (
    .I({ 1'h1, \send.bit_cnt [3], _034_, \send.bit_cnt [2] }),
    .Q(_010_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1010),
    .K(32'sd4)
  ) _162_ (
    .I({ 1'h1, \send.bit_cnt [1], \send.bit_cnt [4], \send.bit_cnt [0] }),
    .Q(_034_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1414),
    .K(32'sd4)
  ) _163_ (
    .I({ 1'h1, \send.bit_cnt [1], _035_, _036_ }),
    .Q(_085_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _164_ (
    .I({ 2'h3, \send.bit_cnt [0], _011_ }),
    .Q(_035_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _165_ (
    .I({ 2'h3, _010_, _011_ }),
    .Q(_036_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _166_ (
    .I({ 2'h3, \send.bit_cnt [2], _037_ }),
    .Q(_086_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _167_ (
    .I({ 2'h3, \send.bit_cnt [1], _035_ }),
    .Q(_037_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0708),
    .K(32'sd4)
  ) _168_ (
    .I({ \send.bit_cnt [3], _036_, \send.bit_cnt [2], _037_ }),
    .Q(_087_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _169_ (
    .I({ \send.bit_cnt [4:2], _037_ }),
    .Q(_088_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _170_ (
    .I({ 2'h3, \send.byte_cnt [0], _036_ }),
    .Q(_089_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _171_ (
    .I({ 1'h1, \send.byte_cnt [1:0], _036_ }),
    .Q(_090_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _172_ (
    .I({ 2'h3, _038_, \send.byte_cnt [2] }),
    .Q(_091_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h8080),
    .K(32'sd4)
  ) _173_ (
    .I({ 1'h1, \send.byte_cnt [1:0], _036_ }),
    .Q(_038_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _174_ (
    .I({ \send.byte_cnt [1:0], \send.byte_cnt [2], _036_ }),
    .Q(_039_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _175_ (
    .I({ 1'h1, \send.byte_cnt [3:2], _038_ }),
    .Q(_092_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _176_ (
    .I({ 1'h1, \send.byte_cnt [4:3], _039_ }),
    .Q(_093_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _177_ (
    .I({ \send.byte_cnt [5:3], _039_ }),
    .Q(_094_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h1111),
    .K(32'sd4)
  ) _178_ (
    .I({ 2'h3, \send.cycle_cnt [0], _011_ }),
    .Q(_095_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _179_ (
    .I({ 2'h3, \send.cycle_cnt [1:0] }),
    .Q(_096_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0708),
    .K(32'sd4)
  ) _180_ (
    .I({ \send.cycle_cnt [2], _011_, \send.cycle_cnt [1:0] }),
    .Q(_097_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _181_ (
    .I({ 2'h3, \send.cycle_cnt [3], _004_ }),
    .Q(_098_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h8080),
    .K(32'sd4)
  ) _182_ (
    .I({ 1'h1, \send.cycle_cnt [1], \send.cycle_cnt [2], \send.cycle_cnt [0] }),
    .Q(_004_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _183_ (
    .I({ 1'h1, \send.cycle_cnt [4:3], _004_ }),
    .Q(_099_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _184_ (
    .I({ \send.cycle_cnt [5:3], _004_ }),
    .Q(_100_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1414),
    .K(32'sd4)
  ) _185_ (
    .I({ 1'h1, \send.cycle_cnt [6], _005_, _011_ }),
    .Q(_101_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _186_ (
    .I({ \send.cycle_cnt [5:3], _004_ }),
    .Q(_005_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _187_ (
    .I({ 1'h1, \send.cycle_cnt [7:6], _005_ }),
    .Q(_102_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'hcaff),
    .K(32'sd4)
  ) _188_ (
    .I({ _046_, _052_, _009_, _006_ }),
    .Q(_103_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h8888),
    .K(32'sd4)
  ) _189_ (
    .I({ 2'h3, _041_, _040_ }),
    .Q(_053_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7f7f),
    .K(32'sd4)
  ) _190_ (
    .I({ 1'h1, \send.byte_cnt [0], _007_, _054_ }),
    .Q(_040_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h1111),
    .K(32'sd4)
  ) _191_ (
    .I({ 2'h3, \send.byte_cnt [3:2] }),
    .Q(_054_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h1111),
    .K(32'sd4)
  ) _192_ (
    .I({ 2'h3, \send.byte_cnt [5:4] }),
    .Q(_007_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1f1f),
    .K(32'sd4)
  ) _193_ (
    .I({ 1'h1, _007_, _008_, _055_ }),
    .Q(_041_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1010),
    .K(32'sd4)
  ) _194_ (
    .I({ 1'h1, \send.byte_cnt [2], \send.byte_cnt [3], \send.byte_cnt [1] }),
    .Q(_055_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0100),
    .K(32'sd4)
  ) _195_ (
    .I({ \send.byte_cnt [1], \send.byte_cnt [3], \send.byte_cnt [0], \send.byte_cnt [2] }),
    .Q(_008_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h1010),
    .K(32'sd4)
  ) _196_ (
    .I({ 1'h1, _034_, \send.bit_cnt [3:2] }),
    .Q(_009_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0100),
    .K(32'sd4)
  ) _197_ (
    .I({ \send.bit_cnt [0], \send.bit_cnt [3], \send.bit_cnt [4], \send.bit_cnt [2] }),
    .Q(_006_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'hbb0f),
    .K(32'sd4)
  ) _198_ (
    .I({ \send.byte_cnt [0], \recv.LED4 , \send.byte_cnt [1], \recv.LED3  }),
    .Q(_042_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'hd3d3),
    .K(32'sd4)
  ) _199_ (
    .I({ 1'h1, _042_, \send.byte_cnt [0], _055_ }),
    .Q(_043_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h07ff),
    .K(32'sd4)
  ) _200_ (
    .I({ \send.bit_cnt [1:0], _041_, _040_ }),
    .Q(_044_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0700),
    .K(32'sd4)
  ) _201_ (
    .I({ _007_, \send.byte_cnt [3:1] }),
    .Q(_000_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0140),
    .K(32'sd4)
  ) _202_ (
    .I({ \send.bit_cnt [2], \send.bit_cnt [3], \send.bit_cnt [0], \send.bit_cnt [4] }),
    .Q(_045_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0700),
    .K(32'sd4)
  ) _203_ (
    .I({ _000_, _010_, _044_, _045_ }),
    .Q(_046_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h110f),
    .K(32'sd4)
  ) _204_ (
    .I({ \send.byte_cnt [0], \recv.LED2 , \send.byte_cnt [5:4] }),
    .Q(_047_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h3500),
    .K(32'sd4)
  ) _205_ (
    .I({ _047_, \send.byte_cnt [2], \recv.LED5 , \send.byte_cnt [3] }),
    .Q(_048_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0d30),
    .K(32'sd4)
  ) _206_ (
    .I({ \send.byte_cnt [0], \send.byte_cnt [1], \send.byte_cnt [2], \recv.LED1  }),
    .Q(_049_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h0700),
    .K(32'sd4)
  ) _207_ (
    .I({ _043_, _053_, _048_, _049_ }),
    .Q(_052_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _208_ (
    .CLK(clk),
    .D(_061_),
    .Q(\recv.bit_cnt [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _209_ (
    .CLK(clk),
    .D(_062_),
    .Q(\recv.bit_cnt [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _210_ (
    .CLK(clk),
    .D(_063_),
    .Q(\recv.bit_cnt [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _211_ (
    .CLK(clk),
    .D(_064_),
    .Q(\recv.bit_cnt [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _212_ (
    .CLK(clk),
    .D(_074_),
    .Q(\recv.cycle_cnt [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _213_ (
    .CLK(clk),
    .D(_075_),
    .Q(\recv.cycle_cnt [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _214_ (
    .CLK(clk),
    .D(_076_),
    .Q(\recv.cycle_cnt [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _215_ (
    .CLK(clk),
    .D(_077_),
    .Q(\recv.cycle_cnt [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _216_ (
    .CLK(clk),
    .D(_078_),
    .Q(\recv.cycle_cnt [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _217_ (
    .CLK(clk),
    .D(_079_),
    .Q(\recv.cycle_cnt [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _218_ (
    .CLK(clk),
    .D(_080_),
    .Q(\recv.cycle_cnt [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _219_ (
    .CLK(clk),
    .D(_081_),
    .Q(\recv.cycle_cnt [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _220_ (
    .CLK(clk),
    .D(_073_),
    .Q(\recv.buffer_valid )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _221_ (
    .CLK(clk),
    .D(_065_),
    .Q(\recv.buffer [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _222_ (
    .CLK(clk),
    .D(_066_),
    .Q(\recv.buffer [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _223_ (
    .CLK(clk),
    .D(_067_),
    .Q(\recv.buffer [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _224_ (
    .CLK(clk),
    .D(_068_),
    .Q(\recv.buffer [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _225_ (
    .CLK(clk),
    .D(_069_),
    .Q(\recv.buffer [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _226_ (
    .CLK(clk),
    .D(_070_),
    .Q(\recv.buffer [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _227_ (
    .CLK(clk),
    .D(_071_),
    .Q(\recv.buffer [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _228_ (
    .CLK(clk),
    .D(_072_),
    .Q(\recv.buffer [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:93.2-115.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _229_ (
    .CLK(clk),
    .D(_082_),
    .Q(\recv.recv )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _230_ (
    .CLK(clk),
    .D(_056_),
    .Q(\recv.LED1 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _231_ (
    .CLK(clk),
    .D(_057_),
    .Q(\recv.LED2 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _232_ (
    .CLK(clk),
    .D(_058_),
    .Q(\recv.LED3 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _233_ (
    .CLK(clk),
    .D(_059_),
    .Q(\recv.LED4 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:44.4-52.3|rs232demo.v:117.2-125.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _234_ (
    .CLK(clk),
    .D(_060_),
    .Q(\recv.LED5 )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _235_ (
    .CLK(clk),
    .D(_089_),
    .Q(\send.byte_cnt [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _236_ (
    .CLK(clk),
    .D(_090_),
    .Q(\send.byte_cnt [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _237_ (
    .CLK(clk),
    .D(_091_),
    .Q(\send.byte_cnt [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _238_ (
    .CLK(clk),
    .D(_092_),
    .Q(\send.byte_cnt [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _239_ (
    .CLK(clk),
    .D(_093_),
    .Q(\send.byte_cnt [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _240_ (
    .CLK(clk),
    .D(_094_),
    .Q(\send.byte_cnt [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _241_ (
    .CLK(clk),
    .D(_084_),
    .Q(\send.bit_cnt [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _242_ (
    .CLK(clk),
    .D(_085_),
    .Q(\send.bit_cnt [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _243_ (
    .CLK(clk),
    .D(_086_),
    .Q(\send.bit_cnt [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _244_ (
    .CLK(clk),
    .D(_087_),
    .Q(\send.bit_cnt [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _245_ (
    .CLK(clk),
    .D(_088_),
    .Q(\send.bit_cnt [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _246_ (
    .CLK(clk),
    .D(_095_),
    .Q(\send.cycle_cnt [0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _247_ (
    .CLK(clk),
    .D(_096_),
    .Q(\send.cycle_cnt [1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _248_ (
    .CLK(clk),
    .D(_097_),
    .Q(\send.cycle_cnt [2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _249_ (
    .CLK(clk),
    .D(_098_),
    .Q(\send.cycle_cnt [3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _250_ (
    .CLK(clk),
    .D(_099_),
    .Q(\send.cycle_cnt [4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _251_ (
    .CLK(clk),
    .D(_100_),
    .Q(\send.cycle_cnt [5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _252_ (
    .CLK(clk),
    .D(_101_),
    .Q(\send.cycle_cnt [6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:146.2-156.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _253_ (
    .CLK(clk),
    .D(_102_),
    .Q(\send.cycle_cnt [7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:56.4-64.3|rs232demo.v:173.2-191.5|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _254_ (
    .CLK(clk),
    .D(_103_),
    .Q(\send.data_bit )
  );
  (* BEL = "IOTILE(04,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:15.49-15.67" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd1),
    .OUTPUT_USED(32'sd0)
  ) clk_ibuf (
    .O(clk)
  );
  (* BEL = "IOTILE(02,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:39.49-39.69" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led1_obuf (
    .I(\recv.LED1 )
  );
  (* BEL = "IOTILE(01,09):alta_rio03" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:36.49-36.69" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led2_obuf (
    .I(\recv.LED2 )
  );
  (* BEL = "IOTILE(00,09):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:33.49-33.69" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led3_obuf (
    .I(\recv.LED3 )
  );
  (* BEL = "IOTILE(00,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:30.49-30.69" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led4_obuf (
    .I(\recv.LED4 )
  );
  (* BEL = "IOTILE(01,09):alta_rio01" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:27.49-27.69" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led5_obuf (
    .I(\recv.LED5 )
  );
  (* BEL = "IOTILE(12,00):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:19.49-19.65" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd1),
    .OUTPUT_USED(32'sd0)
  ) rx_ibuf (
    .O(RX)
  );
  (* BEL = "IOTILE(11,00):alta_rio01" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "rs232demo.v:23.49-23.65" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) tx_ibuf (
    .I(\send.data_bit )
  );
  assign LED1 = \recv.LED1 ;
  assign LED2 = \recv.LED2 ;
  assign LED3 = \recv.LED3 ;
  assign LED4 = \recv.LED4 ;
  assign LED5 = \recv.LED5 ;
  assign TX = \send.data_bit ;
  assign \recv.RX  = RX;
  assign \recv.clk  = clk;
  assign \send.LED1  = \recv.LED1 ;
  assign \send.LED2  = \recv.LED2 ;
  assign \send.LED3  = \recv.LED3 ;
  assign \send.LED4  = \recv.LED4 ;
  assign \send.LED5  = \recv.LED5 ;
  assign \send.TX  = \send.data_bit ;
  assign \send.clk  = clk;
  assign { \send.data_byte [7:6], \send.data_byte [4:3], \send.data_byte [0] } = { 4'h1, \send.data_byte [2] };
endmodule
