/* Generated by Yosys 0.9+2406 (git sha1 5d18fdad, clang 11.0.0 -fPIC -Os) */

/* top =  1  */
/* src = "blinky.v:1.1-31.10" */
module top();
  /* src = "blinky.v:26.1-27.20" */
  wire [25:0] _00_;
  /* src = "blinky.v:27|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" */
  wire _01_;
  /* src = "blinky.v:27|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" */
  wire _02_;
  /* src = "blinky.v:27|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" */
  wire _03_;
  /* src = "blinky.v:27|/usr/local/bin/../share/yosys/techmap.v:295.27-295.69|/usr/local/bin/../share/yosys/techmap.v:238.21-238.22" */
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  /* src = "blinky.v:3.7-3.10" */
  wire clk;
  /* src = "blinky.v:25.12-25.15" */
  wire [25:0] ctr;
  /* src = "blinky.v:7.13-7.17" */
  wire [7:0] leds;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _09_ (
    .I({ 2'h0, ctr[19], _05_ }),
    .Q(_00_[19])
  );
  defparam _09_.INIT = 16'h6666;
  defparam _09_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _10_ (
    .I({ ctr[18], ctr[16], ctr[17], _06_ }),
    .Q(_05_)
  );
  defparam _10_.INIT = 16'h8000;
  defparam _10_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _11_ (
    .I({ ctr[14], ctr[15], ctr[13], _07_ }),
    .Q(_06_)
  );
  defparam _11_.INIT = 16'h8000;
  defparam _11_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _12_ (
    .I({ ctr[12], ctr[10], ctr[11], _08_ }),
    .Q(_07_)
  );
  defparam _12_.INIT = 16'h8000;
  defparam _12_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _13_ (
    .I({ ctr[8], ctr[9], ctr[7], _04_ }),
    .Q(_08_)
  );
  defparam _13_.INIT = 16'h8000;
  defparam _13_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _14_ (
    .I({ ctr[6], ctr[4], ctr[5], _03_ }),
    .Q(_04_)
  );
  defparam _14_.INIT = 16'h8000;
  defparam _14_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _15_ (
    .I({ ctr[2], ctr[3], ctr[1:0] }),
    .Q(_03_)
  );
  defparam _15_.INIT = 16'h8000;
  defparam _15_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _16_ (
    .I({ 1'h0, ctr[20:19], _05_ }),
    .Q(_00_[20])
  );
  defparam _16_.INIT = 16'h7878;
  defparam _16_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _17_ (
    .I({ ctr[21:19], _05_ }),
    .Q(_00_[21])
  );
  defparam _17_.INIT = 16'h7f80;
  defparam _17_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _18_ (
    .I({ 2'h0, ctr[22], _01_ }),
    .Q(_00_[22])
  );
  defparam _18_.INIT = 16'h6666;
  defparam _18_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _19_ (
    .I({ ctr[21:19], _05_ }),
    .Q(_01_)
  );
  defparam _19_.INIT = 16'h8000;
  defparam _19_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _20_ (
    .I({ 1'h0, ctr[23:22], _01_ }),
    .Q(_00_[23])
  );
  defparam _20_.INIT = 16'h7878;
  defparam _20_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _21_ (
    .I({ ctr[24:22], _01_ }),
    .Q(_00_[24])
  );
  defparam _21_.INIT = 16'h7f80;
  defparam _21_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _22_ (
    .I({ 2'h0, ctr[25], _02_ }),
    .Q(_00_[25])
  );
  defparam _22_.INIT = 16'h6666;
  defparam _22_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _23_ (
    .I({ ctr[24:22], _01_ }),
    .Q(_02_)
  );
  defparam _23_.INIT = 16'h8000;
  defparam _23_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _24_ (
    .I({ 2'h0, ctr[1:0] }),
    .Q(_00_[1])
  );
  defparam _24_.INIT = 16'h6666;
  defparam _24_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _25_ (
    .I({ 1'h0, ctr[2:0] }),
    .Q(_00_[2])
  );
  defparam _25_.INIT = 16'h7878;
  defparam _25_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _26_ (
    .I(ctr[3:0]),
    .Q(_00_[3])
  );
  defparam _26_.INIT = 16'h7f80;
  defparam _26_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _27_ (
    .I({ 2'h0, ctr[4], _03_ }),
    .Q(_00_[4])
  );
  defparam _27_.INIT = 16'h6666;
  defparam _27_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _28_ (
    .I({ 1'h0, ctr[5:4], _03_ }),
    .Q(_00_[5])
  );
  defparam _28_.INIT = 16'h7878;
  defparam _28_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _29_ (
    .I({ ctr[6], ctr[4], ctr[5], _03_ }),
    .Q(_00_[6])
  );
  defparam _29_.INIT = 16'h7f80;
  defparam _29_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _30_ (
    .I({ 2'h0, ctr[7], _04_ }),
    .Q(_00_[7])
  );
  defparam _30_.INIT = 16'h6666;
  defparam _30_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _31_ (
    .I({ 1'h0, ctr[8:7], _04_ }),
    .Q(_00_[8])
  );
  defparam _31_.INIT = 16'h7878;
  defparam _31_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _32_ (
    .I({ ctr[9:7], _04_ }),
    .Q(_00_[9])
  );
  defparam _32_.INIT = 16'h7f80;
  defparam _32_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _33_ (
    .I({ 2'h0, ctr[10], _08_ }),
    .Q(_00_[10])
  );
  defparam _33_.INIT = 16'h6666;
  defparam _33_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _34_ (
    .I({ 1'h0, ctr[11:10], _08_ }),
    .Q(_00_[11])
  );
  defparam _34_.INIT = 16'h7878;
  defparam _34_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _35_ (
    .I({ ctr[12], ctr[10], ctr[11], _08_ }),
    .Q(_00_[12])
  );
  defparam _35_.INIT = 16'h7f80;
  defparam _35_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _36_ (
    .I({ 2'h0, ctr[13], _07_ }),
    .Q(_00_[13])
  );
  defparam _36_.INIT = 16'h6666;
  defparam _36_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _37_ (
    .I({ 1'h0, ctr[14:13], _07_ }),
    .Q(_00_[14])
  );
  defparam _37_.INIT = 16'h7878;
  defparam _37_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _38_ (
    .I({ ctr[15:13], _07_ }),
    .Q(_00_[15])
  );
  defparam _38_.INIT = 16'h7f80;
  defparam _38_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" */
  LUT _39_ (
    .I({ 2'h0, ctr[16], _06_ }),
    .Q(_00_[16])
  );
  defparam _39_.INIT = 16'h6666;
  defparam _39_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" */
  LUT _40_ (
    .I({ 1'h0, ctr[17:16], _06_ }),
    .Q(_00_[17])
  );
  defparam _40_.INIT = 16'h7878;
  defparam _40_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" */
  LUT _41_ (
    .I({ ctr[18], ctr[16], ctr[17], _06_ }),
    .Q(_00_[18])
  );
  defparam _41_.INIT = 16'h7f80;
  defparam _41_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:9.33-9.88" */
  LUT _42_ (
    .I({ 3'h0, ctr[0] }),
    .Q(_00_[0])
  );
  defparam _42_.INIT = 8'h55;
  defparam _42_.K = 32'sd4;
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _43_ (
    .CLK(clk),
    .D(_00_[0]),
    .Q(ctr[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _44_ (
    .CLK(clk),
    .D(_00_[1]),
    .Q(ctr[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _45_ (
    .CLK(clk),
    .D(_00_[2]),
    .Q(ctr[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _46_ (
    .CLK(clk),
    .D(_00_[3]),
    .Q(ctr[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _47_ (
    .CLK(clk),
    .D(_00_[4]),
    .Q(ctr[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _48_ (
    .CLK(clk),
    .D(_00_[5]),
    .Q(ctr[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _49_ (
    .CLK(clk),
    .D(_00_[6]),
    .Q(ctr[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _50_ (
    .CLK(clk),
    .D(_00_[7]),
    .Q(ctr[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _51_ (
    .CLK(clk),
    .D(_00_[8]),
    .Q(ctr[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _52_ (
    .CLK(clk),
    .D(_00_[9]),
    .Q(ctr[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _53_ (
    .CLK(clk),
    .D(_00_[10]),
    .Q(ctr[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _54_ (
    .CLK(clk),
    .D(_00_[11]),
    .Q(ctr[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _55_ (
    .CLK(clk),
    .D(_00_[12]),
    .Q(ctr[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _56_ (
    .CLK(clk),
    .D(_00_[13]),
    .Q(ctr[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _57_ (
    .CLK(clk),
    .D(_00_[14]),
    .Q(ctr[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _58_ (
    .CLK(clk),
    .D(_00_[15]),
    .Q(ctr[15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _59_ (
    .CLK(clk),
    .D(_00_[16]),
    .Q(ctr[16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _60_ (
    .CLK(clk),
    .D(_00_[17]),
    .Q(ctr[17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _61_ (
    .CLK(clk),
    .D(_00_[18]),
    .Q(ctr[18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _62_ (
    .CLK(clk),
    .D(_00_[19]),
    .Q(ctr[19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _63_ (
    .CLK(clk),
    .D(_00_[20]),
    .Q(ctr[20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _64_ (
    .CLK(clk),
    .D(_00_[21]),
    .Q(ctr[21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _65_ (
    .CLK(clk),
    .D(_00_[22]),
    .Q(ctr[22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _66_ (
    .CLK(clk),
    .D(_00_[23]),
    .Q(ctr[23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _67_ (
    .CLK(clk),
    .D(_00_[24]),
    .Q(ctr[24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:26.1-27.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" */
  DFF _68_ (
    .CLK(clk),
    .D(_00_[25]),
    .Q(ctr[25])
  );
  /* BEL = "IOTILE(04,09):alta_rio00" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:5.49-5.67" */
  GENERIC_IOB clk_ibuf (
    .O(clk)
  );
  defparam clk_ibuf.INPUT_USED = 32'sd1;
  defparam clk_ibuf.OUTPUT_USED = 32'sd0;
  /* BEL = "IOTILE(02,09):alta_rio00" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:23.49-23.72" */
  GENERIC_IOB led0_obuf (
    .I(ctr[18])
  );
  defparam led0_obuf.INPUT_USED = 32'sd0;
  defparam led0_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(01,09):alta_rio03" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:21.49-21.72" */
  GENERIC_IOB led1_obuf (
    .I(ctr[19])
  );
  defparam led1_obuf.INPUT_USED = 32'sd0;
  defparam led1_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(00,09):alta_rio02" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:19.49-19.72" */
  GENERIC_IOB led2_obuf (
    .I(ctr[20])
  );
  defparam led2_obuf.INPUT_USED = 32'sd0;
  defparam led2_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(00,09):alta_rio00" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:17.49-17.72" */
  GENERIC_IOB led3_obuf (
    .I(ctr[21])
  );
  defparam led3_obuf.INPUT_USED = 32'sd0;
  defparam led3_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(01,09):alta_rio01" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:15.49-15.72" */
  GENERIC_IOB led4_obuf (
    .I(ctr[22])
  );
  defparam led4_obuf.INPUT_USED = 32'sd0;
  defparam led4_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(06,09):alta_rio02" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:13.49-13.72" */
  GENERIC_IOB led5_obuf (
    .I(ctr[23])
  );
  defparam led5_obuf.INPUT_USED = 32'sd0;
  defparam led5_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(07,01):alta_rio00" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:11.49-11.72" */
  GENERIC_IOB led6_obuf (
    .I(ctr[24])
  );
  defparam led6_obuf.INPUT_USED = 32'sd0;
  defparam led6_obuf.OUTPUT_USED = 32'sd1;
  /* BEL = "IOTILE(02,01):alta_rio02" */
  /* keep = 32'd1 */
  /* module_not_derived = 32'd1 */
  /* src = "blinky.v:9.49-9.72" */
  GENERIC_IOB led7_obuf (
    .I(ctr[25])
  );
  defparam led7_obuf.INPUT_USED = 32'sd0;
  defparam led7_obuf.OUTPUT_USED = 32'sd1;
  assign leds = ctr[25:18];
endmodule
