/* Generated by Yosys 0.9+3710 (git sha1 2116c585, clang 12.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "blinky_int_osc_pll.v:1.1-38.10" *)
module top();
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _00_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _01_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _02_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _03_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _04_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _05_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _06_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _07_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _08_;
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire _09_;
  (* force_downto = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _10_;
  (* force_downto = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:34.9-34.19|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [31:0] _11_;
  (* src = "blinky_int_osc_pll.v:22.6-22.13" *)
  wire clk_pll;
  (* src = "blinky_int_osc_pll.v:21.12-21.15" *)
  wire [31:0] ctr;
  (* src = "blinky_int_osc_pll.v:3.13-3.17" *)
  wire [7:0] leds;
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _12_ (
    .I({ 2'h3, ctr[1:0] }),
    .Q(_11_[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _13_ (
    .I({ 1'h1, ctr[2:0] }),
    .Q(_11_[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _14_ (
    .I(ctr[3:0]),
    .Q(_11_[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _15_ (
    .I({ 2'h3, ctr[4], _07_ }),
    .Q(_11_[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _16_ (
    .I(ctr[3:0]),
    .Q(_07_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _17_ (
    .I({ 1'h1, ctr[5:4], _07_ }),
    .Q(_11_[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _18_ (
    .I({ ctr[6:4], _07_ }),
    .Q(_11_[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _19_ (
    .I({ 2'h3, ctr[7], _08_ }),
    .Q(_11_[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _20_ (
    .I({ ctr[6:4], _07_ }),
    .Q(_08_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _21_ (
    .I({ 1'h1, ctr[8:7], _08_ }),
    .Q(_11_[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _22_ (
    .I({ ctr[9:7], _08_ }),
    .Q(_11_[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _23_ (
    .I({ 2'h3, ctr[10], _09_ }),
    .Q(_11_[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _24_ (
    .I({ ctr[9:7], _08_ }),
    .Q(_09_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _25_ (
    .I({ 1'h1, ctr[11:10], _09_ }),
    .Q(_11_[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _26_ (
    .I({ ctr[12:10], _09_ }),
    .Q(_11_[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _27_ (
    .I({ 2'h3, ctr[13], _00_ }),
    .Q(_11_[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _28_ (
    .I({ ctr[12:10], _09_ }),
    .Q(_00_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _29_ (
    .I({ 1'h1, ctr[14:13], _00_ }),
    .Q(_11_[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _30_ (
    .I({ ctr[15:13], _00_ }),
    .Q(_11_[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _31_ (
    .I({ 2'h3, ctr[16], _01_ }),
    .Q(_11_[16])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _32_ (
    .I({ ctr[15:13], _00_ }),
    .Q(_01_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _33_ (
    .I({ 1'h1, ctr[17:16], _01_ }),
    .Q(_11_[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _34_ (
    .I({ ctr[18:16], _01_ }),
    .Q(_11_[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _35_ (
    .I({ 2'h3, ctr[19], _02_ }),
    .Q(_11_[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _36_ (
    .I({ ctr[18:16], _01_ }),
    .Q(_02_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _37_ (
    .I({ 1'h1, ctr[20:19], _02_ }),
    .Q(_11_[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _38_ (
    .I({ ctr[21:19], _02_ }),
    .Q(_11_[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _39_ (
    .I({ 2'h3, ctr[22], _03_ }),
    .Q(_11_[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _40_ (
    .I({ ctr[21:19], _02_ }),
    .Q(_03_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _41_ (
    .I({ 1'h1, ctr[23:22], _03_ }),
    .Q(_11_[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _42_ (
    .I({ ctr[24:22], _03_ }),
    .Q(_11_[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _43_ (
    .I({ 2'h3, ctr[25], _04_ }),
    .Q(_11_[25])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _44_ (
    .I({ ctr[24:22], _03_ }),
    .Q(_04_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _45_ (
    .I({ 1'h1, ctr[26:25], _04_ }),
    .Q(_11_[26])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _46_ (
    .I({ ctr[27:25], _04_ }),
    .Q(_11_[27])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _47_ (
    .I({ 2'h3, ctr[28], _05_ }),
    .Q(_11_[28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _48_ (
    .I({ ctr[27:25], _04_ }),
    .Q(_05_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:15.35-15.90" *)
  LUT #(
    .INIT(16'h7878),
    .K(32'sd4)
  ) _49_ (
    .I({ 1'h1, ctr[29:28], _05_ }),
    .Q(_11_[29])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h7f80),
    .K(32'sd4)
  ) _50_ (
    .I({ ctr[30:28], _05_ }),
    .Q(_11_[30])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:12.34-12.89" *)
  LUT #(
    .INIT(16'h6666),
    .K(32'sd4)
  ) _51_ (
    .I({ 2'h3, ctr[31], _06_ }),
    .Q(_11_[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:18.31-18.63" *)
  LUT #(
    .INIT(16'h8000),
    .K(32'sd4)
  ) _52_ (
    .I({ ctr[30:28], _05_ }),
    .Q(_06_)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:9.33-9.88" *)
  LUT #(
    .INIT(16'h5555),
    .K(32'sd4)
  ) _53_ (
    .I({ 3'h7, ctr[0] }),
    .Q(_10_[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _54_ (
    .CLK(clk_pll),
    .D(_11_[17]),
    .Q(ctr[17])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _55_ (
    .CLK(clk_pll),
    .D(_11_[18]),
    .Q(ctr[18])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _56_ (
    .CLK(clk_pll),
    .D(_11_[19]),
    .Q(ctr[19])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _57_ (
    .CLK(clk_pll),
    .D(_11_[20]),
    .Q(ctr[20])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _58_ (
    .CLK(clk_pll),
    .D(_11_[21]),
    .Q(ctr[21])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _59_ (
    .CLK(clk_pll),
    .D(_11_[22]),
    .Q(ctr[22])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _60_ (
    .CLK(clk_pll),
    .D(_11_[23]),
    .Q(ctr[23])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _61_ (
    .CLK(clk_pll),
    .D(_11_[24]),
    .Q(ctr[24])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _62_ (
    .CLK(clk_pll),
    .D(_11_[25]),
    .Q(ctr[25])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _63_ (
    .CLK(clk_pll),
    .D(_11_[26]),
    .Q(ctr[26])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _64_ (
    .CLK(clk_pll),
    .D(_11_[27]),
    .Q(ctr[27])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _65_ (
    .CLK(clk_pll),
    .D(_11_[28]),
    .Q(ctr[28])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _66_ (
    .CLK(clk_pll),
    .D(_11_[29]),
    .Q(ctr[29])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _67_ (
    .CLK(clk_pll),
    .D(_11_[30]),
    .Q(ctr[30])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _68_ (
    .CLK(clk_pll),
    .D(_11_[31]),
    .Q(ctr[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _69_ (
    .CLK(clk_pll),
    .D(_10_[0]),
    .Q(ctr[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _70_ (
    .CLK(clk_pll),
    .D(_11_[1]),
    .Q(ctr[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _71_ (
    .CLK(clk_pll),
    .D(_11_[2]),
    .Q(ctr[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _72_ (
    .CLK(clk_pll),
    .D(_11_[3]),
    .Q(ctr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _73_ (
    .CLK(clk_pll),
    .D(_11_[4]),
    .Q(ctr[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _74_ (
    .CLK(clk_pll),
    .D(_11_[5]),
    .Q(ctr[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _75_ (
    .CLK(clk_pll),
    .D(_11_[6]),
    .Q(ctr[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _76_ (
    .CLK(clk_pll),
    .D(_11_[7]),
    .Q(ctr[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _77_ (
    .CLK(clk_pll),
    .D(_11_[8]),
    .Q(ctr[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _78_ (
    .CLK(clk_pll),
    .D(_11_[9]),
    .Q(ctr[9])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _79_ (
    .CLK(clk_pll),
    .D(_11_[10]),
    .Q(ctr[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _80_ (
    .CLK(clk_pll),
    .D(_11_[11]),
    .Q(ctr[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _81_ (
    .CLK(clk_pll),
    .D(_11_[12]),
    .Q(ctr[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _82_ (
    .CLK(clk_pll),
    .D(_11_[13]),
    .Q(ctr[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _83_ (
    .CLK(clk_pll),
    .D(_11_[14]),
    .Q(ctr[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _84_ (
    .CLK(clk_pll),
    .D(_11_[15]),
    .Q(ctr[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:33.1-34.20|/Users/swhite/Projects/rodinia/nextpnr/synth/cells_map.v:23.48-23.89" *)
  DFF _85_ (
    .CLK(clk_pll),
    .D(_11_[16]),
    .Q(ctr[16])
  );
  (* BEL = "IOTILE(02,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:19.49-19.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led0_obuf (
    .I(ctr[24])
  );
  (* BEL = "IOTILE(01,09):alta_rio03" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:17.49-17.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led1_obuf (
    .I(ctr[25])
  );
  (* BEL = "IOTILE(00,09):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:15.49-15.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led2_obuf (
    .I(ctr[26])
  );
  (* BEL = "IOTILE(00,09):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:13.49-13.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led3_obuf (
    .I(ctr[27])
  );
  (* BEL = "IOTILE(01,09):alta_rio01" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:11.49-11.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led4_obuf (
    .I(ctr[28])
  );
  (* BEL = "IOTILE(06,09):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:9.49-9.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led5_obuf (
    .I(ctr[29])
  );
  (* BEL = "IOTILE(07,01):alta_rio00" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:7.49-7.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led6_obuf (
    .I(ctr[30])
  );
  (* BEL = "IOTILE(02,01):alta_rio02" *)
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:5.49-5.72" *)
  GENERIC_IOB #(
    .INPUT_USED(32'sd0),
    .OUTPUT_USED(32'sd1)
  ) led7_obuf (
    .I(ctr[31])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "blinky_int_osc_pll.v:24.13-30.2" *)
  GENERIC_PLL #(
    .CLKOUT0_DIV(6'h02)
  ) pll (
    .clkfb(clk_pll),
    .clkout0(clk_pll),
    .clkout0en(1'h1),
    .pllen(1'h1),
    .resetn(1'h1)
  );
  assign _10_[31:1] = ctr[31:1];
  assign _11_[0] = _10_[0];
  assign leds = ctr[31:24];
endmodule
